jekyll:
    image: kaerast/rake-preview
    ports:
        - 4000:4000
    volumes:
        - .:/usr/src/app
gulp:
    image: agomezmoron/docker-gulp
    environment:
        - GULP_TASK="watch"
    volumes:
        - .:/src
